

const getAllUsers = async (req, res) => {
    try {

    } catch (error) {
        res.status(500).json({ error: `Internal server error: ${error.message}` });
    }
};

const getUser = async (req, res) => {
    try {

    } catch (error) {
        res.status(500).json({ error: `Internal server error: ${error.message}` });
    }
};

const addUser = async (req, res) => {
    try {

    } catch (error) {
        res.status(500).json({ error: `Internal server error: ${error.message}` });
    }
};

const updateUser = async (req, res) => {
    try {

    } catch (error) {
        res.status(500).json({ error: `Internal server error: ${error.message}` });
    }
};

const deleteUser = async (req, res) => {
    try {

    } catch (error) {
        res.status(500).json({ error: `Internal server error: ${error.message}` });
    }
};

module.exports = { getAllUsers, getUser, addUser, updateUser, deleteUser };;